### ISSUE TITLE
store round data in variables to call for post game "history"

### ISSUE THREAD

**Issue by djkean** [djkean/FoodForAll#27]
current code is removing the contents of the container in order to make room for each new round to be played, this is an approach to still keeping all that information to use at the end of the game while still keeping the "game space" tidy

const roundData = [
roundDataN (n = the round that information came from
make an array of objects(?), each object being a round and all of the text from actions for that round 
at the end oft he game, call roundData and display the text from each round that was played in order)
]

**Comment by jackharrhy** [comment]
![image](https://user-images.githubusercontent.com/6486417/162593089-1633831a-93fc-4283-ba0d-9d4559562557.png)

example shown in april 9th session on actionsHistory

![image](https://user-images.githubusercontent.com/6486417/162593098-f54df707-eb48-4296-9276-a7eb9ef17065.png)

**Comment by jackharrhy** [comment]
- [ ] create a new list called `roundActions` near `playerInfo` / `playerNext`, that is empty
- [ ] create another list called `actionsHistory`, similar to `roundActions`
- [ ] before you `return player, event;`, push to `roundActions` with the `action`
- [ ] within `nextRound`, push the `roundActions` into `actionsHistory`, and then reset `roundsActions` to an empty array
